### ISSUE TITLE
Global toggle ProofMode on/off

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#16]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/5701152/208917871-d2da1f27-b11d-4b33-b3e0-73085660632f.png">

_([See full size on Mural](https://app.mural.co/t/starlinglab7814/m/starlinglab7814/1670031264455/7780f1cf9640f67862a28fc883630ccaa915d24a?sender=ub3a421c048efd7d270741703))_

This task aims to create a ProofMode item in Signal Settings, which directs to a page explaining briefly what ProofMode is about. On this page, it is possible to globally opt out of ProofMode features.

In this case, #10  features are off by default and #13 features are reverted back on.

**Comment by maxSafronovForte** [comment]
https://github.com/starlinglab/signal-x-proofmode/pull/20
