### ISSUE TITLE
Update, reword Settings copy

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#25]
Updates and follows #20.

![Image](https://user-images.githubusercontent.com/5701152/209172604-43c8c5d7-c1f3-44dd-89bd-cf4c447c2d38.png)

**Comment by basilesimon** [comment]
@maxSafronovForte Can the copy below the toggles be dynamic?

**Comment by maxSafronovForte** [comment]
yep, it can be

**Comment by maxSafronovForte** [comment]
Can we close this issue @basilesimon ?

**Comment by basilesimon** [comment]
Yes thanks
