### ISSUE TITLE
Held: Decision on what to send

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#27]
# Options regarding sharing a ProofMode-enhanced media

In this situation:
    - I have captured a photograph through Custom Signal Build
    - ProofMode proofs were generated (location, device ID, etc.)
    - I have selected the contact(s) with whom I want to share this rich media.

**What, precisely, should go to the Contact(s)?**

Candidates to be included are:  
    - Some text as part of the message (the *Message*),
    - The photograph itself (the *Photo*),
    - The ZIP file of ProofMode proofs (the *Proofs ZIP*),
    - The link to the MobileCoin ledger notarizing the capture (the *MobileCoin registration link*).

Something to keep in mind: The person-to-person workflow includes the idea that as the receiver of such a bundle, we will have *some visual feedback* about its qualities (think green check marks or locks), or show some of the proofs. 
To this effect, having the ZIP file in a single, isolated message might (?) make it easier to de-serialise and pull data out of?

**1. Send, in one go, all assets?**  
    Well-formatted string containing Message + Registration link
    Plus two attachments: the Photo + a ZIP file

**2. Send (Message + Photo) together, then ZIP, then Registration**  
    Feels quite natural to have Message and Photo together,
    But might be costly to have further steps "taking over" your Signal,
    engineering-wise, changes-wise, and UX-wise.

**3. ???**  
    what did i miss

**Comment by n8fr8** [comment]
As mentioned in voice message, I vote for #1, with the caveat that the MobileCoin registration info will be stored within the proofzip as a notary output.

**Comment by basilesimon** [comment]
Option 1 seems to have gathered the most votes, so let me recap the flow:

- I have captured a photograph through Custom Signal Build
- ProofMode proofs were generated (location, device ID, etc.)
- I have selected the contact(s) with whom I want to share this rich media
- OUTDATED, see below message: The receiver of the message gets _one_ message from me:
    - The photo I took,
    - The ZIP of ProofMode proofs,
    - The text I wrote + a string we programmatically set, ideally

**Comment by basilesimon** [comment]
To reflect that we can't have ZIP + JPEG, we need two messages:

- I have captured a photograph through Custom Signal Build
- ProofMode proofs were generated (location, device ID, etc.)
- I have selected the contact(s) with whom I want to share this rich media
- The receiver of the message gets _two_ message from me:
    - One: The photo I took,
    - Two: The ZIP of ProofMode proofs, as well as the text I wrote + a string we programmatically set, ideally

**Comment by n8fr8** [comment]
Busy with family, but I want to make the case for just sending a proof zip with the photo/video inside of it. This will block any compression/modification that might happen as well.

We can build a custom proof viewer that dynamically pulls out a thumbnail from the proof zip to render it for viewing.

**Comment by basilesimon** [comment]
@maxSafronovForte  – could you also place a copy of the original captured file inside the ProofMode zip, to address Nathan's concern?

**Comment by n8fr8** [comment]
Yes, please do that. We also need to put the pubkey.asc into the zip file. I will add sample code for how that is done to the project, or can implement a PR myself.

**Comment by basilesimon** [comment]
@maxSafronovForte  – See both messages above 🙏
