### ISSUE TITLE
Generate ProofMode proofs when a photo is captured through Signal camera

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#3]

**Comment by maxSafronovForte** [comment]
When I do

 var proofHash = ProofMode.generateProof(context, uri)

proofHash = null

I use uri just from the Photo which I've made via Signal

**Comment by maxSafronovForte** [comment]
This blocks me

**Comment by maxSafronovForte** [comment]
https://github.com/starlinglab/signal-x-proofmode/pull/15
