### ISSUE TITLE
Re-design proofs toggles

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#32]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/5701152/210005357-a1f0f37e-7c03-4ff2-9b43-5e326986c91d.png">

**Comment by maxSafronovForte** [comment]
Not clear for me, what the data we need to fill there
Because in new ui case I need to get all this data manually
And this ui need discussions

**Comment by basilesimon** [comment]
Closed by #46 .
