### ISSUE TITLE
Attach photo and ZIP of proofs when a photo is captured

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#4]

**Comment by maxSafronovForte** [comment]
Need to remove access to Crop, Rotate, Draw functionality

**Comment by basilesimon** [comment]
Could we _keep_ the buttons where they are but:
1. Disable them (clicking doesn't trigger a function)
2. Dim/ grey them out to indicate they're disabled?

**Comment by maxSafronovForte** [comment]
to my mind it will confused users why they can't do this
if we want to implement grey color and disabling them, we need to implement pop up dialog which will explain, why we disable them

**Comment by basilesimon** [comment]
Agree with you, although the user base is a couple of trained individuals, so we are fine with quirky behaviour. 

For now let’s disable and grey out the buttons for MVP. I’ll add the task to add an explanation pop up to a later sprint, in a week or so.

**Comment by maxSafronovForte** [comment]
Sure, thanks!

**Comment by basilesimon** [comment]
Just making sure #27 cross pollinates, let me recap the flow:

- I have captured a photograph through Custom Signal Build
- ProofMode proofs were generated (location, device ID, etc.)
- I have selected the contact(s) with whom I want to share this rich media
- The receiver of the message gets _two_ message from me:
    - One: The photo I took,
    - Two: The ZIP of ProofMode proofs, as well as the text I wrote + a string we programmatically set, ideally

**Comment by maxSafronovForte** [comment]
Can we close this issue @basilesimon ?

**Comment by basilesimon** [comment]
Yes thanks
