### ISSUE TITLE
Download of ZIP on file system missing file extension (.zip)

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#42]

**Comment by maxSafronovForte** [comment]
It's still zip
It can't be missing

**Comment by basilesimon** [comment]
I needed to add the `.zip` extension, as opposed to, in the screenshot below, a valid zip (the signal-android one).

![Screenshot_20230103-170356](https://user-images.githubusercontent.com/5701152/210394911-c3e308dc-af1b-443d-be68-00673a978c65.png)

**Comment by maxSafronovForte** [comment]
Can close this
@basilesimon
