### ISSUE TITLE
Put the pubkey.asc into the zip file

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#43]

**Comment by maxSafronovForte** [comment]
Is it default behaviour ?
Because I use that example, which Nathan gave me

**Comment by basilesimon** [comment]
Linked to #39

**Comment by n8fr8** [comment]
@maxSafronovForte I think the example has the pubkey.asc being imported into the proofzip. Can you point me to the spot in the code where you implemented this, so I can review?

**Comment by maxSafronovForte** [comment]
I can find the key in all my zip files, which I sent

**Comment by maxSafronovForte** [comment]
@basilesimon , please, check it

**Comment by basilesimon** [comment]
Found it in the new ZIPs, thanks.
