### ISSUE TITLE
Proof UI (on send) not rendering

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#48]
Report from Jonathan on [Thu 4 Jan evening build](https://starlinglabhq.slack.com/archives/C04FY71N63B/p1672858287871819):

![Image](https://user-images.githubusercontent.com/5701152/210867776-44147da9-f7aa-48f1-95ef-a8e707dae8bd.png)

**Comment by basilesimon** [comment]
I can reproduce this bug if I hit "Camera" while on the conversation screen.

If I hit "Camera" from the main app home screen _then_ pick a contact, it works fine. Asking Jonathan to try as well.

**Comment by basilesimon** [comment]
Confirm that we can all reproduce this bug. @maxSafronovForte you're on the right track 😊

**Comment by maxSafronovForte** [comment]
For now this bug should be no longer reproducible with latest build which I shared in Slack
