### ISSUE TITLE
Deactivate / grey out "+" button permitting upload from photo gallery

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#49]

**Comment by n8fr8** [comment]
If you choose + -> File and choose a JPG from there, everything works as expected. So perhaps there is a way to leave the + feature available, but just handle the "imported from gallery" logic differently than the "captured with in app camera"?

**Comment by maxSafronovForte** [comment]
If we want to handle this new behaviour, need to spend much more time, so will hide this feature
Will leave Proof Mode for photos only

**Comment by maxSafronovForte** [comment]
For now implemented Proof Mode feature for Photo button from main screen only
