### ISSUE TITLE
ZIP filename should be the hash of the ZIP

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#54]
Sorry :(

**Comment by maxSafronovForte** [comment]
Already implemented

**Comment by basilesimon** [comment]
@maxSafronovForte Can you confirm whether you're using the hash of the Photo or of the ZIP?
Using CLI or an online tool I'm not able to compute the right hash for either.

**Comment by maxSafronovForte** [comment]
I use photo hash and this hash we have in json file

**Comment by basilesimon** [comment]
OK, thanks – so that title is right.

Presently, we’re using the photo’s hash to name the bundle/ZIP

I’d like that we use the bundle/ZIP’s hash to name the bundle 🙏

**Comment by basilesimon** [comment]
@maxSafronovForte I'm still not able to confirm this is the case. I would like the ZIP file's filename to be the ZIP file's hash value if possible?

**Comment by basilesimon** [comment]
I can now confirm the ZIP's filename is the hash of the media – [as per here](https://github.com/starlinglab/signal-x-proofmode/blob/da924309a129a874921e2a7032ceb05c6ee3b760/app/src/main/java/org/thoughtcrime/securesms/mediasend/v2/MediaSelectionRepository.kt#L98).
