### ISSUE TITLE
Add photo to ZIP, so it validates

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#64]
From Nathan:

> Ah right, the photo! That's the problem. I thought that was already happening.
> The photo should be the saw raw bytes that you used to generate the proof hash. Do not re-encode.

**Comment by n8fr8** [comment]
the photo should be named using the last segment of the URI path provided to proofmode

"File Path": "content:\/\/org.thoughtcrime.securesms.blob\/blob\/single-session-disk\/image%2Fjpeg\/null\/281306\/a2867d92-ea35-4e47-986d-46ae472f451b",

photo should be named
a2867d92-ea35-4e47-986d-46ae472f451b.jpg

**Comment by n8fr8** [comment]
Also, when the URI is passed from Signal into libProofMode, it should have the ".jpg" extension appended on to it

content://org.thoughtcrime.securesms.blob/blob/single-session-disk/image%2Fjpeg/null/281306/a2867d92-ea35-4e47-986d-46ae472f451b.jpg

Filename for Zip:
a2867d92-ea35-4e47-986d-46ae472f451b.jpg
