### ISSUE TITLE
Automatic build of `.apk` from release

### ISSUE THREAD

**Issue by basilesimon** [starlinglab/signal-x-proofmode#8]

**Comment by basilesimon** [comment]
To check: Bitrise invite

**Comment by basilesimon** [comment]
Ok @n8fr8 I've joined bitrise!

**Comment by n8fr8** [comment]
Bitrise build configured, but seems to hang before it can complete. Checking on that now.

**Comment by n8fr8** [comment]
This is somewhat working now, but only against my personal dev branch. Will work to get it building off of max's main.

**Comment by basilesimon** [comment]
Yeah let's leave the Issue open. What would you think about triggering builds from release/tags only?

**Comment by n8fr8** [comment]
I can enable selective builds, if I am added as a member of the project on github.

**Comment by basilesimon** [comment]
I've added you as maintainer to the repository, Nathan.

**Comment by n8fr8** [comment]
You should see a request from bitrise or github about enabling access.

**Comment by basilesimon** [comment]
Just approved that :)

**Comment by n8fr8** [comment]
Now done via private Bitrise CI/CD configuration
